### ISSUE TITLE
how to test the logging

### ISSUE THREAD

**Issue by rox117** [msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore#2]
After i've setup as you've shown in the readme, how do i test database logging

**Comment by msmolka** [comment]
You can look at my tests. For Unit Testing I'm using InMemory provider: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.InMemory/

This allows simplify testing without real DB preservation.

**Comment by rox117** [comment]
I was looking at your StartupExtended example and i saw that you used a WithFilter function on the loggerfactory. I cant seem to find that function

**Comment by msmolka** [comment]
for `WithFilter` you will need standard filter package:
`"Microsoft.Extensions.Logging.Filter": "1.1.0",`

**Comment by rox117** [comment]
Where in the TestLoggerExtended class does the log actually get written to the database

**Comment by msmolka** [comment]
`EntityFrameworkLogger` is responsible for writing data to database
