### ISSUE TITLE
Connect Timeout with MySQL

### ISSUE THREAD

**Issue by mguinness** [msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore#3]
When using your library with MySQL I was getting the following exception:

`MySql.Data.MySqlClient.MySqlException: Connect Timeout expired.`

I was able to save a Log entity manually which was meant that the database connection was good.  Before giving up, I came across issue https://github.com/msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore/issues/1 which explained the problem.

It would be very helpful if you included the WithFilter configuration in README.md and made a brief mention of the issue as I'm sure it would help others in the same predicament.

In addition, as this is a known issue, wouldn't it be a good idea to include the following code in the WriteMessage method in EntityFrameworkLogger class?

```
if (!this.Name.StartsWith("Microsoft.EntityFrameworkCore"))
    context.SaveChanges();
```

**Comment by msmolka** [comment]
Hi, Thank you for advice. 
I've added both: information about log filters and preventing log `Microsoft.EntityFrameworkCore`

**Comment by mguinness** [comment]
Thanks for your work on the library
