### ISSUE TITLE
Stop exception handling?

### ISSUE THREAD

**Issue by DWalkit** [msmolka/ZNetCS.AspNetCore.Logging.EntityFrameworkCore#5]
I'm trying your logging package in my new Core 2.0 project and quickly discovered that it was swallowing up exceptions that my custom middleware usually handled.  My custom exception logging middleware logs to SQL and sends emails to admin staff.  Doesn't seem to matter how I set the FilterLoggerSettings, your package seems to handle exceptions - but then I'll lose my emailing and separate exception logging.  I really wanted your logging framework to just log the messages I send it (like the built in Asp.Net Core logging, but to SQL).

Is it possible that the order of my app.UseNNNNNNN in Startup.Configure() could be changed?  Currently I have them ordered:
UseStatusCodePagesWithReExecute()
UseExceptionLoggingMiddleware()  <--- my custom middleware
UseExceptionHandler()

loggerFactory.WithFilter( [just like your example])

UseStaticFiles()
UseAuthentication()
UseMvc()

Thanks for any tips!

**Comment by msmolka** [comment]
I'm surprised, if you look into code there is no exception handling inside. There is no explicit by MVC filters like `ExceptionHandled` (because there is no exception handling inside) and there is also no try catch inside.
It is just additional logger provider to write log using Entity Framework Core.

Are there any exceptions? Maybe something is throwing exception and stops your middleware.

**Comment by DWalkit** [comment]
I know, I browsed your code and saw no try/catch.  Strange!

I haven't seen any additional exceptions, my middleware works without your logger, and never gets called with your logger.  I'll take a really hard look at my debug output and let you know if I see anything that might give us a clue.

Thank you for your time!

**Comment by msmolka** [comment]
Maybe there is other issue there, some exception that breaks execution

**Comment by DWalkit** [comment]
Strange, now my middleware isn't working, even without your logger.  Odd as I haven't touched it in two days, maybe the latest VS 2017 update did something.  I guess the problem is mine, sorry to have brought this up, but again, thank you!

**Comment by msmolka** [comment]
So closing...

**Comment by DWalkit** [comment]
Hello Marcin,

I figured out my <self-inflicted> issue and both wanted to thank you again
and apologize if I was any trouble!

Merry Christmas/Happy Holidays!

David
